### PR TITLE
fix show/hide style options

### PR DESCRIPTION
**Pull request by ellie-xyb**
Make the invisible style options div `display: none`, because the invisible div was stopping me from clicking the buttons on the widget.
Screen Shot 2021-08-15 at 17 27 27

### CODE REVIEW

**Comment by ellie-xyb** [comment]
@polanpio this was commented out, was there a reason for it?

**Comment by polanpio** [comment]
the only reason for that is, when display has none and block, the animations lacks smoothness, div appears very abruptly, if it’s operated by opacity it looks way smoother

**Comment by ellie-xyb** [comment]
I'll try to fix that, just a moment

**Comment by ellie-xyb** [comment]
@polanpio can you please take a look at it now? I think I've fixed the animations.

**Comment by polanpio** [comment]
cool, let’s go with your changes

**Comment by ellie-xyb** [comment]
Thanks! I'll merge it

**Pull request merged**
