### PR TITLE
replace font-awesome icons with feather and svg file

### PR DESCRIPTION
**Pull request by ellie-xyb**
The font-awesome icons doesn't work with webpack(I need use webpack to generate the finial widget script.)
I changed to use svg version and feather icons.

Screen Shot 2021-08-19 at 22 54 52

### CODE REVIEW

**Review by polanpio — COMMENTED** [review]
looks very nice, we will have to adjust other icons to same style ;)

**Comment by ellie-xyb** [comment]
font-awesome icons on the sidebar will work as usual. Which one do you want to change style?

**Comment by polanpio** [comment]
now that I’m thinking about it. If we don’t have any repeating icons we can stick with what we have

**Comment by ellie-xyb** [comment]
Yeah! Let's stick with what we have for now. will merge it.

**Pull request merged**
