### PR TITLE
Youtube content preview

### PR DESCRIPTION
**Pull request by ellie-xyb**
1. Render sidebar in the widgets/:id/edit page.
2. Did basic youtube video preview card design.
3. Noticed the issues @polanpio mentioned the other day when the right-side content is over 100vh. Let's fix this in another PR.
Screen Shot 2021-08-13 at 16 35 10

Screen Shot 2021-08-13 at 16 33 53

Screen Shot 2021-08-13 at 16 36 07

### CODE REVIEW

**Comment by polanpio** [comment]
I did similar changes in index.html.erb, so more conflicts ;p

**Comment by polanpio** [comment]
Looks fine to merge but will cause a lot of conflicts with what I have in my current code. First thing we do tomorrow should resolving all of these and having clean master.

**Comment by ellie-xyb** [comment]
I worry tomorrow might be a busy day. Is your current code ready to push and merge?  
Then I can try to merge this pr and solve the conflicts tonight?

**Comment by polanpio** [comment]
I'm trying to figure out the highlights they were working and suddenly stopped.. Size is more or less working, background is fine, fonts and layout definitely need what's in this PR to target the right divs. Selim's part is working, logout button is fixed.

for solving conflicts we definitely need all parties involved, cause the way all structure code in different

**Pull request merged**
